trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: Image-Repo
  value: ataylorregistry.azurecr.io
- name: Image-Name
  value: ksam
- name: Image-Tag
  value: 1.0 

steps:
- task: AzureKeyVault@1
  displayName: 'Download secrets'
  inputs:
    azureSubscription: 'AKS'
    KeyVaultName: 'KSAM'
    SecretsFilter: 'Az-Client-Id,Az-Client-Secret,Az-Tenant-Id,CR-Username,CR-Password'
    RunAsPreJob: false

- task: replacetokens@3
  displayName: 'Replace tokens in Dockerfile'
  inputs:
    targetFiles: '**/Dockerfile'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    useLegacyPattern: false
    enableTelemetry: true

- task: CmdLine@2
  displayName: 'Build Docker image'
  inputs:
    script: |
      docker build -t ${{ variables.Image-Repo }}/${{ variables.Image-Name }}:${{ variables.Image-Tag }} .

- task: CmdLine@2
  displayName: 'Push Docker image'
  inputs:
    script: |
      docker login ${{ variables.Image-Repo }} --username $(CR-Username) --password $(CR-Password)
      docker push ${{ variables.Image-Repo }}/${{ variables.Image-Name }}:${{ variables.Image-Tag }}