kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: test-access
    namespace: test
rules:
 - apiGroups: ["*"]
   resources: ["*"]
   verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: test-access
    namespace: test
subjects:
- kind: ServiceAccount
  name: test-service-account
  namespace: test
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: test-access