apiVersion: v1
kind: Namespace
metadata:
    name: {{ namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ namespace }}-service-account
    namespace: {{ namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: {{ namespace }}-access
    namespace: {{ namespace }}
rules:
 - apiGroups: ["*"]
   resources: ["*"]
   verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: {{ namespace }}-access
    namespace: {{ namespace }}
subjects:
- kind: ServiceAccount
  name: {{ namespace }}-service-account
  namespace: {{ namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ namespace }}-access